services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command:
      [
        '-path',
        '/migrations',
        '-database',
        'postgres://user:password@postgres:5432/warehouse_db?sslmode=disable',
        'up',
      ]
    depends_on:
      - postgres

  MEDIA-PROJECT:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
